# which benchmarks to run
benchmarks = '../test/ssa/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.ssa]
pipeline = [
  "bril2json",
  "python3 ssa.py",
  "brili -p {args}",
]
